### ISSUE TITLE
Build error?

### ISSUE THREAD

**Issue by nguyenlau** [SANdood/Aeon-HEM-v2#3]
I tried to build this code last night and this morning in the SmartThings IDE, and I keep getting this error message below. It's a very cryptic error message, and tried to google/debug but was not successful.  Did ST change their compiler/interpreter or something, causing this code to no longer compile? Can someone try to duplicate this at the SmartThings cloud IDE, or is it localized to me somehow?

Sorry, and please let me know if this isn't the correct place to post this "issue". Thanks!

No signature of method: script14454442332241874674061.metadata() is applicable for argument types: (script14454442332241874674061$_run_closure1) values: [script14454442332241874674061$_run_closure1@587d0e12] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by bkeifer** [comment]
Make sure you're creating a new device type, not a new smartapp.

**Comment by nguyenlau** [comment]
Thanks so much!  That was the issue.  I would have wasted much more time, if it wasn't for your advice.  Rgds -- Lau
      From: Brian Keifer notifications@github.com

Make sure you're creating a new device type, not a new smartapp.—
