### ISSUE TITLE
I tried to add this today, and got this message, admit I'm new to groovy

### ISSUE THREAD

**Issue by txbone66** [SANdood/Aeon-HEM-v2#6]
No signature of method: script14514874388591874674061.metadata() is applicable for argument types: (script14514874388591874674061$_run_closure1) values: [script14514874388591874674061$_run_closure1@74369ff1] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure) 

Any ideas?

**Comment by SANdood** [comment]
Make sure you are using the source code to make a SmartDevice and not a SmartApp 

Thanks!
      Barry

**Comment by txbone66** [comment]
Thanks for the input.  I did that and was able to get the device type updated.  Cheers.

**Comment by txbone66** [comment]
Barry, I’ve got my power meter up and running and figured out the logging to get the data over to xifely.  

2 questions.  1 I’m new to smartthings having just changed over from VeraEdge (junk).  Over there, we paid for code, which I don’t mind when I get stuff working…  Is that the case over here, i.e. where we can donate?
1.  Any suggestions on why the kwh is coming in with no data?  I can see it on the device, just not xifely...

**Comment by txbone66** [comment]
I removed and readded the device and now it's logging everything.  Thanks for your help...
